name: Simple FileStorage Service CI/CD

on:
  push:
    branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Dockerhub
        id: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build, Tag, and Push image to dockerhub
        id: build-image
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
          DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
          IMAGE_TAG: latest
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG  
          echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


  Continuous-Deployment:
      needs: Continuous-Integration
      runs-on: self-hosted

      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Stop and remove all Docker containers and images
        run: |
          docker ps -q | xargs -r docker stop
          docker ps -aq | xargs -r docker rm
          docker images -q | xargs -r docker rmi -f

      - name: Run Docker Image
        run: |
          docker run -d \
          -e B2_ACCESS_KEY_ID="${{ secrets.B2_ACCESS_KEY_ID }}" \
          -e B2_APPLICATION_KEY="${{ secrets.B2_APPLICATION_KEY }}" \
          -e B2_BUCKET_NAME="${{ secrets.B2_BUCKET_NAME }}" \
          -e B2_S3_ENDPOINT_URL-"${{ secrets.B2_S3_ENDPOINT_URL }}" \
          -e DOCKER_REPOSITORY="${{ secrets.DOCKER_REPOSITORY }}" \
          -e DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" \
          -e DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_PASSWORD }}" \
          -p 8000:8000 "${{ secrets.DOCKER_REGISTRY }}"/"${{ secrets.DOCKER_REPOSITORY }}":latest
