name: Simple FileStorage Service CI/CD

on:
  push:
    branches: [main]
  pull-request:
      branches: [main]

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Login to Dockerhub
          id: docker-login
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}

        - name: Build, Tag, and Push image to dockerhub
          id: build-image
          env:
            DOCKER_REGISTRY: ${{ steps.docker-login.outputs.registry }}
            DOCKER_REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
            IMAGE_TAG: latest

        - name: Build Docker Image
          run: docker build -t $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG .
          
        - name: Push Docker Image to Dockerhub
          run: docker push $DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAGE 
            echo "image=$DOCKER_REGISTRY/$DOCKER_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT


  Continuous-Deployment:
      need: Continuous-Integration
      run-on: self-hosted

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Run Docker Image
          run: |
            docker run -d \
            -e B2_ACCESS_KEY_ID="${{ secrets.B2_ACCESS_KEY_ID }}" \
            -e B2_APPLICATION_KEY="${{ secrets.B2_APPLICATION_KEY }}" \
            -e B2_BUCKET_NAME="${{ secrets.B2_BUCKET_NAME }}" \
            -e S3_ENDPOINT_URL-"${{ secrets.S3_ENDPOINT_URL }}" \
            -e DOCKER_REPOSITORY="${{ secrets.DOCKER_REPOSITORY }}" \
            -e DOCKERHUB_USERNAME="${{ secrets.DOCKERHUB_USERNAME }}" \
            -e DOCKERHUB_TOKEN="${{ secrets.DOCKERHUB_PASSWORD }}" \
            -p 8000:8000 "${{ steps.docker-login.outputs.registry }}"\"${{ secrets.DOCKER_REPOSITORY }}":latest